### PR TITLE
  build(packaging): add eslint airbnb-base and airbnb-typescript/base styleguide

### PR DESCRIPTION
**Pull request by robots4life**
1. `npx --yes npm-check-updates`
2. `npx npm-check-updates -u`
3. `npm install -D eslint-plugin-prettier`
4. `npx install-peerdeps --dev eslint-config-airbnb-base`
5. `npm install eslint-config-airbnb-typescript --save-dev`
6. `npm install -D eslint-import-resolver-typescript`
7. add needed vscode settings
8. edit `.eslintrc.cjs`
9. add npm script `eslint`

- linting now works with the airbnb-base and airbnb-typescript/base styleguide
- prettier runs as a plugin of eslint
- both linting and formatting automatically on save or via command line works

### CODE REVIEW

**Comment by haladamateusz** [comment]
Hello Robert,

First of all, thanks for your hard work!

I really appreciate that. It's great, but still requires some small fixes/cleanups.

Let's start with the PR description.

Steps:
`npx --yes npm-check-updates` - It installs the ncu package in `_npx` directory [(further reading here)](https://stackoverflow.com/a/67030685/6762379). Since this package is very handy, it's worth  to use it across all projects that we are working on. Therefore, I would recommend to install it globally with `npm install -g npm-check-updates`. Then, anytime when you want to update any of your projects, you can simply run `ncu` in root to check if any updates are available, or `ncu -u` to update them all.

`npx npm-check-updates -u` - update of packages is not related to scope of this PR. Please remove all of changes in `package.json` which are not related to eslint/prettier.

`npm install -D eslint-plugin-prettier` - please go through Prettier official documentation related to [integrating with linters](https://prettier.io/docs/en/integrating-with-linters.html). Remove `eslint-plugin-prettier` in favor of `[eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)`

`npx install-peerdeps --dev eslint-config-airbnb-base` - everything correct!

`npm install eslint-config-airbnb-typescript --save-dev` - great job!

`npm install -D eslint-import-resolver-typescript` - can you explain why this thing is needed?

`add needed vscode settings` - .vscode/ folder should be in .gitignore. Some developers use Intellij IDE, which doesn't profit from .vscode/ folder. Therefore, pushing editor settings to repo should be avoided. Please remove it and add .vscode/ folder to .gitignore.

`edit .eslintrc.cjs` - great!

`add npm script eslint` - eslint should be run without --fix flag. It can introduce mess in the code and make tracking of changes difficult.

Can you also explain, why changes to `ts.config.json` were needed? Why in `include` array you put `.svelte-kit/` folder, which is built automatically by SvelteKit and not even included in repo files? Same question about tests/ folder. They are not there yet. If you want to specify selector for all typescript files, go for `**/*.ts`. It will catch them all :)

**Comment by robots4life** [comment]
> Steps: `npx --yes npm-check-updates` - It installs the ncu package in `_npx` directory [(further reading here)](https://stackoverflow.com/a/67030685/6762379). Since this package is very handy, it's worth to use it across all projects that we are working on. Therefore, I would recommend to install it globally with `npm install -g npm-check-updates`. Then, anytime when you want to update any of your projects, you can simply run `ncu` in root to check if any updates are available, or `ncu -u` to update them all.

Sure will do that. :+1: 


> `npx npm-check-updates -u` - update of packages is not related to scope of this PR. Please remove all of changes in `package.json` which are not related to eslint/prettier.

If the packages are **not** updated it is **not** possible to integrate prettier with eslint.
Here you can see the errors that follow when trying to install `eslint-plugin-prettier` without doing any updates on the given packages versions.
[https://github.com/robots4life/airbnb-eslint-prettier-sveltekit#4](https://github.com/robots4life/airbnb-eslint-prettier-sveltekit#4)
I might open an issue with Svelte to find out why the versions of the default skeleton template are not up to date and eplain that there are errors when trying to add eslint/prettier to the repo and see what they say. I tried many different way and always faced errors, only when updating all the packages with `ncu` would ensuing installation of eslint/prettier packages work fine.

> `npm install -D eslint-plugin-prettier` - please go through Prettier official documentation related to [integrating with linters](https://prettier.io/docs/en/integrating-with-linters.html). Remove `eslint-plugin-prettier` in favor of `[eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)`

Prettier should run as a plugin of ESLint and not standalone to avoid formatting errors between ESLint and Prettier. We could also get rid of Prettier altogether, if we like to keep Prettier I would say run it as a plugin of ESLint. Here is also a good explanation in more details. [https://youtu.be/y068wjb4XtI?feature=shared&t=2978](https://youtu.be/y068wjb4XtI?feature=shared&t=2978)

> `npx install-peerdeps --dev eslint-config-airbnb-base` - everything correct!

:+1: 

> `npm install eslint-config-airbnb-typescript --save-dev` - great job!

:+1: 

> `npm install -D eslint-import-resolver-typescript` - can you explain why this thing is needed?

This is needed to that `$lib` and `$app` aliases can be resolved with TypeScript.
[https://github.com/robots4life/airbnb-eslint-prettier-sveltekit#10](https://github.com/robots4life/airbnb-eslint-prettier-sveltekit#10)
[https://github.com/CodingGarden/listd/blob/main/tsconfig.json](https://github.com/CodingGarden/listd/blob/main/tsconfig.json)

> `add needed vscode settings` - .vscode/ folder should be in .gitignore. Some developers use Intellij IDE, which doesn't profit from .vscode/ folder. Therefore, pushing editor settings to repo should be avoided. Please remove it and add .vscode/ folder to .gitignore.

Sure will do that. :+1: 

> `edit .eslintrc.cjs` - great!

:+1: 

> `add npm script eslint` - eslint should be run without --fix flag. It can introduce mess in the code and make tracking of changes difficult.

Sure will do that. :+1: 

> Can you also explain, why changes to `ts.config.json` were needed? Why in `include` array you put `.svelte-kit/` folder, which is built automatically by SvelteKit and not even included in repo files? Same question about tests/ folder. They are not there yet. If you want to specify selector for all typescript files, go for `**/*.ts`. It will catch them all :)

I removed the `.svelte-kit` and `test` folders from the include and added `"**/*.js", "**/*.ts"` and it works so far, if we face issues later on we can always come back to the include. As far as I remember there was a specific reason to keep the `.svelte-kit` folder in there as outlined here [https://github.com/robots4life/airbnb-eslint-prettier-sveltekit#11](https://github.com/robots4life/airbnb-eslint-prettier-sveltekit#11) and all the info in that. To sum up, it works so far by removing them, I will do that for now. :+1:

**Comment by haladamateusz** [comment]
> Prettier should run as a plugin of ESLint and not standalone to avoid formatting errors between ESLint and Prettier. We could also get rid of Prettier altogether, if we like to keep Prettier I would say run it as a plugin of ESLint. Here is also a good explanation in more details. https://youtu.be/y068wjb4XtI?feature=shared&t=2978

What do you think is a better source: eight months old youtube video or [Prettier documentation](https://prettier.io/docs/en/integrating-with-linters.html)?

From prettier.io:
_When searching for both Prettier and your linter on the Internet you’ll probably find more related projects. These are generally not recommended, but can be useful in certain circumstances._

> If the packages are not updated it is not possible to integrate prettier with eslint.
> Here you can see the errors that follow when trying to install eslint-plugin-prettier without doing any updates on the given packages versions.
> https://github.com/robots4life/airbnb-eslint-prettier-sveltekit#4
> I might open an issue with Svelte to find out why the versions of the default skeleton template are not up to date and eplain that there are errors when trying to add eslint/prettier to the repo and see what they say. I tried many different way and always faced errors, only when updating all the packages with ncu would ensuing installation of eslint/prettier packages work fine.

If we use suggest way of linters integration, we don't need to update Prettier to v3.

> I removed the .svelte-kit and test folders from the include and added "**/*.js", "**/*.ts" and it works so far, if we face issues later on we can always come back to the include. As far as I remember there was a specific reason to keep the .svelte-kit folder in there as outlined here https://github.com/robots4life/airbnb-eslint-prettier-sveltekit#11 and all the info in that. To sum up, it works so far by removing them, I will do that for now.

Linking your private repo with notes is not the best way to explain things. header #11 contains one YT link mentioned three times. How should I make use of it?  **As far as I remember there was a specific reason to keep the .svelte-kit folder in there as outlined here** - please give exact explanation next time.

**Comment by robots4life** [comment]
> > Prettier should run as a plugin of ESLint and not standalone to avoid formatting errors between ESLint and Prettier. We could also get rid of Prettier altogether, if we like to keep Prettier I would say run it as a plugin of ESLint. Here is also a good explanation in more details. https://youtu.be/y068wjb4XtI?feature=shared&t=2978
> 
> What do you think is a better source: eight months old youtube video or [Prettier documentation](https://prettier.io/docs/en/integrating-with-linters.html)?

Do we want to run Prettier standalone or as a plugin of ESLint ? I suggest using Prettier as a plugin of ESLint.

It is not so much about the age of the youtube video but rather the working code from the repo where many people work on it and more so the reasoning behind using Prettier standalone or as a plugin of ESLint.
[https://github.com/CodingGarden/listd/blob/main/.eslintrc.cjs#L10](https://github.com/CodingGarden/listd/blob/main/.eslintrc.cjs#L10)

If you like to use Prettier standalone then I assume this PR will not cut it since this PR is about using Prettier as a plugin of ESLint, either way, I don't mind.

Beyond the Prettier docs, what other advantages do you see in using Prettier standalone, perhaps from your experience you have some key points I am not aware of and that could be helpful to decide what to do.

> 
> From prettier.io: _When searching for both Prettier and your linter on the Internet you’ll probably find more related projects. These are generally not recommended, but can be useful in certain circumstances._
> 
> > If the packages are not updated it is not possible to integrate prettier with eslint.
> > Here you can see the errors that follow when trying to install eslint-plugin-prettier without doing any updates on the given packages versions.
> > https://github.com/robots4life/airbnb-eslint-prettier-sveltekit#4
> > I might open an issue with Svelte to find out why the versions of the default skeleton template are not up to date and eplain that there are errors when trying to add eslint/prettier to the repo and see what they say. I tried many different way and always faced errors, only when updating all the packages with ncu would ensuing installation of eslint/prettier packages work fine.
> 
> If we use suggest way of linters integration, we don't need to update Prettier to v3.

That is the quesiton we should decide, use Prettier standalone or as ESLint plugin, I would opt for the latter.

edit: Does that mean you like to keep Prettier under v3 in order to have airbnb styleguide working with ESLint ? Or does that mean any updates on Prettier in the future will not affext the ESLint airbnb styleguide integration ?

> 
> > I removed the .svelte-kit and test folders from the include and added "**/*.js", "**/*.ts" and it works so far, if we face issues later on we can always come back to the include. As far as I remember there was a specific reason to keep the .svelte-kit folder in there as outlined here https://github.com/robots4life/airbnb-eslint-prettier-sveltekit#11 and all the info in that. To sum up, it works so far by removing them, I will do that for now.
> 
> Linking your private repo with notes is not the best way to explain things. header #11 contains one YT link mentioned three times. How should I make use of it? **As far as I remember there was a specific reason to keep the .svelte-kit folder in there as outlined here** - please give exact explanation next time.

The repo is public, yes I will try to provide a detailed explanation.

**Comment by haladamateusz** [comment]
> That is the quesiton we should decide, use Prettier standalone or as ESLint plugin, I would opt for the latter.

We need to distinguish tools between code formatter and linter. Linter takes care of code quality and good practices. Formatter doesn't care about used functions and approaches taken in code development. It just formats what is inside files.

We want to run prettier 'on save', when developer got this option enabled in his IDE. Therefore, we need prettier to be a totally independent entity.

We want to run linter in pre-commit hook later on with husky. In programming, you should always modularize everything as much as possible - it leads to more elastic code base and easier refactor in the future.

> edit: Does that mean you like to keep Prettier under v3 in order to have airbnb styleguide working with ESLint ? Or does that mean any updates on Prettier in the future will not affext the ESLint airbnb styleguide integration ?

It is a problem related to eslint-plugin-prettier, which we are not going to use.

**Comment by robots4life** [comment]
Excellent, thank you for the detailed explanation, makes a lot of sense.

I will go through [https://github.com/prettier/eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) and use that and once done push the changes to this PR including the changes outlined [here](https://github.com/haladamateusz/storycoder-svelte/pull/2#issuecomment-1788867811).

If you have any experience in using [https://github.com/prettier/eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) or any caveats to look out for when settting that up, let me know, thank you.

Going back into the config labyrinth. :smile: :scream: :sunglasses:

**Comment by haladamateusz** [comment]
You can refer to this article - https://medium.com/tbc-engineering/why-and-how-to-lint-like-a-pro-173fc4a73899

**Pull request closed without merging**
